#!/usr/bin/env bash

unset INSTALL_PYTHON

if [ -x /usr/local/bin/python3 ]; then
    INSTALL_PYTHON=/usr/local/bin/python3
elif [ -x /usr/bin/python3 ]; then
    INSTALL_PYTHON=/usr/bin/python3
fi
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -n "$INSTALL_PYTHON" ] && "${INSTALL_PYTHON}" -c "import pre_commit" >/dev/null 2>&1 ; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
