name: Pull Request CI/CD Flow

on:
  pull_request:

jobs:
  test:
    name: Unit Test Project
    runs-on: ubuntu-latest
    container: jwhouse/github-actions-agent:latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | sed -e 's/refs\/heads\///g')"
      - name: Execute tests
        run: make -C Tests test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/TEST-*.xml'
  validate-version:
    name: Validate Version
    runs-on: ubuntu-latest
    container: jwhouse/github-actions-agent:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current version
        id: version
        run: echo "::set-output name=version::v$(make -V VERSION)"
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
      - name: Validate tag
        run: |
          if [ -n "$(echo '${{steps.tagger.outputs.tag}}' | grep "$${{ steps.version.outputs.version }}")" ]; then
            echo "Git tag for version $${{ steps.version.outputs.version }} exists!"
            exit 1
          fi
