name: Pull Request CI/CD Flow

on:
  pull_request:

jobs:
  test:
    name: Unit Test Project
    runs-on: ubuntu-latest
    container: jwhouse/github-actions-agent:latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | sed -e 's/refs\/heads\///g')"
      - name: Execute tests
        run: make -C Tests test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/TEST-*.xml'
